//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eX_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlackBoxData
    {
        public int ID { get; set; }
        public Nullable<int> DroneID { get; set; }
        public Nullable<int> FlightID { get; set; }
        public Nullable<int> BBFlightID { get; set; }
        public Nullable<int> Record_ { get; set; }
        public Nullable<int> Drone_Serial { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<decimal> Lon { get; set; }
        public Nullable<decimal> Alt { get; set; }
        public Nullable<decimal> Speed { get; set; }
        public Nullable<int> FixQuality { get; set; }
        public Nullable<int> Satellites { get; set; }
        public string RecordTime { get; set; }
        public Nullable<decimal> Pitch { get; set; }
        public Nullable<decimal> Roll { get; set; }
        public Nullable<decimal> Heading { get; set; }
        public Nullable<int> TotalFlightTime { get; set; }
    }
}
