//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eX_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightInfo
    {
        public int ID { get; set; }
        public Nullable<int> FlightID { get; set; }
        public string Condition { get; set; }
        public Nullable<decimal> WindSpeed { get; set; }
        public Nullable<decimal> Humidity { get; set; }
        public Nullable<decimal> Visibility { get; set; }
        public Nullable<decimal> Pressure { get; set; }
        public Nullable<decimal> Temperature { get; set; }
        public Nullable<decimal> Wind { get; set; }
        public Nullable<decimal> MaxAltiude { get; set; }
        public Nullable<decimal> MinAltitude { get; set; }
        public Nullable<decimal> AvgAltitude { get; set; }
        public Nullable<decimal> MaxSpeed { get; set; }
        public Nullable<decimal> MinSpeed { get; set; }
        public Nullable<decimal> AvgSpeed { get; set; }
        public Nullable<decimal> MaxSatellites { get; set; }
        public Nullable<decimal> MinSatellites { get; set; }
        public Nullable<decimal> AvgSatellites { get; set; }
    }
}
