//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eX_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSTR_Drone_TechnicalLogDetails
    {
        public string PlaceFrom { get; set; }
        public string PlaceTo { get; set; }
        public Nullable<System.TimeSpan> TakeOffTime { get; set; }
        public Nullable<System.TimeSpan> LandingTime { get; set; }
        public Nullable<System.TimeSpan> FlightTime { get; set; }
        public string Battery1ID { get; set; }
        public Nullable<decimal> B1StartingVoltage { get; set; }
        public Nullable<decimal> B1EndingVoltage { get; set; }
        public string Battery2ID { get; set; }
        public Nullable<decimal> B2StartingVoltage { get; set; }
        public Nullable<decimal> B2EndingVoltage { get; set; }
        public int Id { get; set; }
    }
}
