//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eX_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSTR_Drone
    {
        public int DroneId { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<int> ManufactureId { get; set; }
        public Nullable<int> UavTypeId { get; set; }
        public Nullable<int> PartsGroupId { get; set; }
        public string DroneName { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string DroneIdBitString { get; set; }
        public Nullable<int> RecordType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string DroneIdHexa { get; set; }
        public string DroneIdBarCode { get; set; }
    }
}
