//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eX_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSTR_Pilot_Log
    {
        public int Id { get; set; }
        public Nullable<int> DroneId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string RouteFrom { get; set; }
        public string RouteTo { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> SimulatedInstrument { get; set; }
        public Nullable<int> AsflightInstructor { get; set; }
        public Nullable<int> DualRecieved { get; set; }
        public Nullable<int> FloatingCommand { get; set; }
        public Nullable<int> PilotId { get; set; }
        public Nullable<int> FixedWing { get; set; }
        public Nullable<int> MultiDashRotor { get; set; }
    }
}
