//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eX_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSTR_Drone_TechnicalLog
    {
        public Nullable<System.DateTime> Date { get; set; }
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
