//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eX_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayLoadTrafficData
    {
        public long ID { get; set; }
        public Nullable<int> FrameNumber { get; set; }
        public Nullable<int> VehicleCount { get; set; }
        public Nullable<decimal> TimeFrame { get; set; }
        public Nullable<int> FlightVideoID { get; set; }
        public Nullable<int> FlightID { get; set; }
        public Nullable<int> IsProcessed { get; set; }
        public Nullable<System.DateTime> CreatedTimestamp { get; set; }
    }
}
